export const FRUITS = [
  {
    id: 1,
    title: 'Grape Viognier - 500g, Georgia',
    imageUrl: require('../Pictures/grapes.png'),
    price: 'SAR 9.25',
    newArrival: false,
    sale: false,
  },
  {
    id: 2,
    title: 'Bnanas - 1kg, Egypt',
    imageUrl: require('../Pictures/bnana.png'),
    price: 'SAR 9.55',
    newArrival: false,
    sale: false,
  },
  {
    id: 3,
    title: 'Kiwi Kings - 1kg, Spain',
    imageUrl: require('../Pictures/kiwi.png'),
    price: 'SAR 9.25',
    newArrival: false,
    sale: false,
  },
  {
    id: 4,
    title: 'Strawberries - 1 pack, 500g, Ukraine',
    imageUrl: require('../Pictures/strawberry.png'),
    price: 'SAR 9.25',
    newArrival: true,
    sale: false,
  },
  {
    id: 5,
    title: 'Blueberries - 1 pack, 250g',
    imageUrl: require('../Pictures/blueberry.png'),
    price: 'SAR 9.25',
    newArrival: true,
    sale: false,
  },
  {
    id: 6,
    title: 'Apples Golden - 1kg, Ukraine',
    imageUrl: require('../Pictures/apples.png'),
    price: 'SAR 9.25',
    newArrival: false,
    sale: false,
  },
  {
    id: 7,
    title: 'Orange Juicy Blue, 1-kg, Spain',
    imageUrl: require('../Pictures/oranges.png'),
    price: 'SAR 9.25',
    newArrival: false,
    sale: false,
  },
  {
    id: 8,
    title: 'Mandarines Sweetie - 1 kg, Spain',
    imageUrl: require('../Pictures/mandarines.png'),
    price: 'SAR 9.25',
    newArrival: false,
    sale: false,
  },
  {
    id: 9,
    title: 'Fresh Pineapple, 1pc, Cosa Rica',
    imageUrl: require('../Pictures/pineapple.png'),
    price: 'SAR 9.25',
    price2: 'SAR 10.50',
    newArrival: false,
    sale: true,
  },
];
